
name: build

on:
  push:
  pull_request:
    branches:
      - "**" # Don't trust forks because miners

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test

